name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test

  security:
    runs-on: ubuntu-24.04
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Start Application
        run: |
          npm start &
          sleep 5 # Wait for the application to start to run OWASP ZAP

      - name: Run OWASP ZAP (Updated Image)
        run: |
          docker pull zaproxy/zap-stable
          docker run --rm -v $(pwd):/zap/wrk:rw zaproxy/zap-stable zap-full-scan.py -t http://localhost:3000 -r zap_report.html
          docker pull zaproxy/zap-stable
          docker run --rm -v $(pwd):/zap/wrk:rw zaproxy/zap-stable zap-full-scan.py -t http://localhost:3000 -r zap_report.html

  deploy:
    runs-on: ubuntu-24.04
    needs: security
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: '${{ secrets.DOCKER_USERNAME }}'
          password: '${{ secrets.DOCKER_PASSWORD }}'

      - name: Push Docker Image
        run: |
          docker build -t lacrei-api .
          docker tag lacrei-api:latest ${DOCKER_USERNAME}/lacrei-api:latest
          docker push ${DOCKER_USERNAME}/lacrei-api:latest
