name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test

  security:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run OWASP ZAP
        uses: zaproxy/action-full-scan@v0.5.0
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'
          target: http://localhost:3000

  deploy:
    runs-on: ubuntu-latest
    needs: security
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: '${{ secrets.DOCKER_USERNAME }}'
          password: '${{ secrets.DOCKER_PASSWORD }}'

      - name: Push Docker Image
        run: |
          docker build -t lacrei-api .
          docker tag lacrei-api:latest ${DOCKER_USERNAME}/lacrei-api:latest
          docker push ${DOCKER_USERNAME}/lacrei-api:latest